# Generated by Django 2.0.6 on 2018-06-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_bith',
            new_name='date_of_birth',
        ),
    ]
