# Generated by Django 2.0.6 on 2018-07-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=[''], null=True, on_delete='CASCADE', related_name='target_obj', to='contenttypes.ContentType'),
        ),
    ]
