# Generated by Django 2.0.6 on 2018-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20180729_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
    ]
